import { ArrowRight, ShieldCheck } from 'lucide-react'

const brands = ['ChatSEO', 'Abyssale', 'BlogSEO', 'lemlist', 'folk', 'Leadbay', 'Ringover', 'Attio', 'La Growth Machine', 'gojiberry']

export default function Home() {
  return (
    <main className="min-h-screen bg-linear-to-b from-sky-100 via-blue-50 to-white">

      {/* Hero */}
      <section className="flex flex-col items-center justify-center min-h-[88vh] px-6 text-center">
        <div className="flex items-center gap-2 bg-white/80 border border-black/10 rounded-full px-4 py-2 text-sm text-gray-600 mb-8 shadow-sm">
          <span className="font-semibold text-black">𝕏</span>
          <span className="text-blue-600 font-semibold">in</span>
          Where B2B brands work with creators
        </div>

        <h1 className="text-6xl md:text-7xl font-black text-gray-900 max-w-4xl leading-tight mb-6">
          The B2B LinkedIn<br />Creator Marketplace.
        </h1>

        <p className="text-xl text-gray-500 max-w-2xl mb-10 leading-relaxed">
          Find the creators your buyers already trust, launch campaigns in days, and track the clicks, leads and pipeline generated by every post.
        </p>

        <div className="flex flex-col sm:flex-row items-center gap-4 mb-10">
          <a href="/register" className="flex items-center gap-2 bg-black text-white px-8 py-4 rounded-full hover:bg-black/80 transition-colors font-medium">
            Launch a campaign <ArrowRight className="w-4 h-4" />
          </a>
          <a href="#how-it-works" className="flex items-center gap-2 text-gray-700 px-8 py-4 rounded-full border border-black/15 hover:bg-black/5 transition-colors font-medium">
            See how Naano works <ArrowRight className="w-4 h-4" />
          </a>
        </div>

        <div className="flex items-center gap-2 text-sm text-gray-400">
          <ShieldCheck className="w-4 h-4" />
          Trusted by modern B2B teams
        </div>
      </section>

      {/* Logo Marquee */}
      <section className="py-10 overflow-hidden border-t border-black/5 bg-white/40">
        <div className="flex animate-marquee gap-16 whitespace-nowrap">
          {[...brands, ...brands].map((brand, i) => (
            <span key={i} className="text-gray-400 font-semibold text-sm tracking-wide">
              {brand}
            </span>
          ))}
        </div>
      </section>

      {/* Testimonial */}
      <section className="py-24 px-6 bg-gray-50 flex flex-col items-center text-center">
        <div className="mb-6">
          <div className="border border-gray-300 px-6 py-3 inline-block tracking-widest text-sm font-semibold text-gray-700 uppercase">
            &#123; zmirov &#125;<br />
            <span className="text-[10px] tracking-[0.3em] font-normal">COMMUNICATION</span>
          </div>
          <div className="w-10 h-0.5 bg-blue-500 mx-auto mt-3" />
        </div>

        <blockquote className="max-w-4xl text-4xl md:text-5xl font-bold text-gray-900 leading-tight mb-12">
          &quot;We manage €10M+ of influence budget every year. For B2B, Naano simply makes our life{' '}
          <span className="text-blue-300">easier</span>&quot;
        </blockquote>

        <div className="flex flex-col items-center gap-3">
          <div className="w-16 h-16 rounded-full bg-gray-400 flex items-center justify-center text-white font-semibold text-lg">
            DZ
          </div>
          <div>
            <p className="font-semibold text-gray-900">David Zmirov</p>
            <p className="text-sm text-gray-500">CEO, Zmirov Communication</p>
            <p className="text-sm text-gray-400">Influence agency</p>
          </div>
        </div>
      </section>

    </main>
  )
}